Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -28,12 +28,16 @@ jobs:
       id: determine-version
       run: |
         VERSION=$(npx semantic-release --dry-run | grep "next release version" | awk '{print $NF}')
+        if [ -z "$VERSION" ]; then
+          echo "Error: VERSION is empty"
+          exit 1
+        fi
         echo "VERSION=$VERSION" >> $GITHUB_ENV
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
     - name: Login to Docker Hub
-      run: echo "${{ vars.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
     - name: Build and Push Docker Image
       run: |
@@ -43,11 +47,12 @@ jobs:
 
     - name: Update Changelog and Commit
       run: |
+        git config user.name "GitHub Actions"
+        git config user.email "actions@github.com"
         git pull --rebase
         npx semantic-release changelog
         git add CHANGELOG.md
-        git commit -m "chore(release): update changelog [skip ci]"
-        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Petros2505/github-actions.git HEAD:main"
+        git commit -m "chore(release): update changelog [skip ci]" || echo "No changes to commit"
         git push
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
